sudo: required
dist: trusty
addons:
    artifacts: {paths: [results]}
    apt: {sources: [google-chrome], packages: [google-chrome-stable]}
language: node_js
node_js:
    - '7'
cache:
    directories: [node_modules, bower_components, $HOME/.npm, $HOME/.cache]
before_script:
    - 'npm install'
before_deploy:
    - 'npm run build'
env:
    global: [NODE_ENV=testing, ARTIFACTS_BUCKET=javascript-automation, {secure: GldOTW/2vm5Bjpt9zFiK+WfuANAt4buXL2PTlxFrVoUUvi64yaArs54xermm/TBAR0TSJ2du/byZ5a9sVgeDUlkrMPGL4qgJg05pPPwwXRjuc3zUL2JJndyl57bfEeRq73Oxoq71UE1BXvjmkup0dCMRT/kD8GpjVgN+H8POUtSV5Q/nCh5RWXFX4pFGP6amklu+FPa+14A8qM0PtefuBK1FztRcbO64i586ceSy+WTFk4liKhDk/uZVZkJ5Q9vNklnh1SX9m+d+POBT/muAjqhLyC7CY/0GrAfTrAioDJ3GxUFGFoEXKLg4TC+KncZDVwLUL2p/qJ/Oq4gZ02VBPi30o2yX8DEUQty02hKwf019qrVBpylMSL4NAHrAb44M/LjHg7or5KQmSb1Zfu8lMv7QBkc5on2sgdUWd70gPLypze22en9Zr/q8cPzDy7qrVBPgAm1FuuPs8O63A6u8ZCQZQtEuaYJsGrkLJfi82v3deDyUccrC1zggV25GRecjsFpw9QQ7zLPwXJDbDhjdMNIWYB0ts29JBo6kXJKxLUjV+jJipZXucasDVxCSy2OsqsnRL4vlUaV2ecEkU6W1pmfGyVdZ6yuN/Uvp4/KNtQ23wZWVwv0XZMeyH4uHn7ZRm9ERg3PI07hxx0LkI/GCG7JMc0MpdlCnTiPId235nUM=}, {secure: YPM1+Kt8gOC1Byudcze71z6+xH1CpcHdGtOxpNZ9LYCKGIFW7JN/gYUr8NWV0uZKvlOVM5yXO0dO6abnJ7yomQTVX532B8O97ocfgzev0fdVaH4n2MYdy+n6UY1zcHJOattBzfKctOPpZwEoSnYwi39UnfxqUufbr4Hj60hRuLZvVe1yYH65A/fKHmxlN2pFFQIVxEnERaeiIIsb2CBSg9aVHi3hHMMgvv7+nLV7n7zDIPfcjva2SFm9/ttIUSewFft7s+Tfx59FEx6fpqCZm6Vqep2ljXwzaYmaiCDiMk1PJCFeG56y4BV3kF65dO2Owhe+0yMyh3xbfgIx8+wqFl6rZVNW9QoRpoirU1QNCN9a/65utmUXTImcdipIMutGOJFSeVKPU96hFWw/3L1/cx/N9JacSCKHhHBYXHpx0Uf6CpxC1r8yK9O/pmjo5TWBKvZFCIHZ7cP1ylY8DDch2vUu0EkgPVO+64Q51SX06w+gawY2O33Y6u7IqjsbHm9K/eUiNjgODdSDnfs2Yl/MlgbPlROF08Rk5pisoOfXu3uF/UOOADFYF2XoTLCsUIt01wJJIOg3ijzxsXhC0CD4a+qcAoOT4H15cHwZKsJfjUVJEEjNQD852qkyqZzZni1LAysyWXgyDwlPnLT5waQWWK39fjOlMpjMG/qRYZnJ/3Y=}]
script:
    - 'npm run test'
notifications:
    webhooks: 'http://ec2-54-234-52-201.compute-1.amazonaws.com/automation/ci/build'
